---
site:
  code: ffgh
  tld:  ffgh # optional, defaults to code
  mesh:
    network:
      ipv4: 10.100.0.0/16
      ipv6: fd2c:2342:1337::/48
    network_dynamic_clients: # optional, defaults to network.ipv6
      ipv6: fd2c:2342:1337::/64

  mesh_vpn:
    peer_limit: 100 # optional, defaults to no limit
    mtu: 1280
    key_git: https://github.com/TobleMiner/ffgh-fastd-peers.git
    port: 11235
    verify: yes # optional, defaults to yes

  bgp:
    as: 65525

  dns:
    ffki:
      git: git://git.freifunk.in-kiel.de/ffki-zone.git
      servers:
        - 127.0.0.1@5300
        - ::1@5300

  ffnw:
    network:
      ipv6: 2a07:59c6:ec02::/48

  noc_keys:
    git: https://github.com/TobleMiner/ffki-noc-sshkeys.git

batman:
  version: 2013.4.0-11
