---
dependencies:
  - { role: node_l2 }
  - { role: router }
  - role: dhcp_server
    vars:
      dhcp_iface: br-{{ site.code }}
      dhcp_network: '{{ interface.mesh_bridge.address.ipv4 | ipaddr("0") }}'
      dhcp_options:
        routers: '{{ interface.mesh_bridge.dhcp_gateway | strip_prefixlen if interface.mesh_bridge.dhcp_gateway is defined else interface.mesh_bridge.address.ipv4 | strip_prefixlen }}'
        domain-name-servers:
          - '{{ interface.mesh_bridge.address.ipv4 | strip_prefixlen }}'
          - '{{ interface.mesh_bridge.address.ipv4 | strip_prefixlen }}'
        domain-name: '"{{ site.tld if site.tld is defined else site.code }}"'
        ntp-servers: '{{ interface.mesh_bridge.address.ipv4 | strip_prefixlen }}'
      dhcp_range: '{{ interface.mesh_bridge.dhcp_range }}'
      dhcp_lease_time:
        min: 120
        default: 300
        max: 600
  - role: dns_iterator
    vars:
      dns_iface: br-{{ site.code }}
      dns_listen:
        - '{{ interface.mesh_bridge.address.ipv4 | strip_prefixlen }}'
        - '{{ interface.mesh_bridge.address.ipv6 | strip_prefixlen }}'
      dns_acl:
        - '{{ interface.mesh_bridge.address.ipv4 | ipaddr("0") }}'
        - '{{ interface.mesh_bridge.address.ipv6 | ipaddr("0") }}'
      dns_zones: '{{ site.dns }}'
  - role: dns_authoritative
    vars:
      dns_zones: '{{ site.dns }}'
  - role: radvd
    vars:
      ra_iface: br-{{ site.code }}
      ra_default_lifetime: 1200
      ra_interval:
        max: 200
      ra_prefixes:
        - prefix: '{{ site.mesh.network_dynamic_clients.ipv6 if site.mesh.network_dynamic_clients is defined else site.mesh.network.ipv6 }}'
          lifetime:
            preferred: 14400
            valid: 86400
      ra_dns_servers:
        - '{{ interface.mesh_bridge.address.ipv6 | strip_prefixlen }}'
      
