---
dependencies:
  - role: router
  - role: firewall_mss_clamp
    vars:
      iface: wg-{{ site.code }}+
      mss: '{{ (site_l3.mtu | default(1410)) - 60 }}'
  - role: wireguard_p2p
    vars:
      wireguard:
        peers: '{{ site_l3.peers }}'
        key:   '{{ site_l3.key }}'
        mtu:   '{{ site_l3.mtu | default(False) }}'
      wireguard_alias: gateway_site_l3
  - role: bird4
    vars:
      bird_device_routes: yes
  - role: bird6
    vars:
      bird6_device_routes: yes
  - role: interface_manual
    vars:
      iface: '{{ interface.lan.name }}'
      iface_hotplug: yes
      iface_scripts:
        inet:
          pre-up:    ip addr add {{ interface.lan.address.ipv4 }} dev $IFACE || true
          up:        ip link set up dev $IFACE
          post-up:   systemctl restart dhcpd || true
          post-down: ip addr del {{ interface.lan.address.ipv4 }} dev $IFACE || true
        inet6:
          pre-up:    ip addr add {{ interface.lan.address.ipv6 }} dev $IFACE || true
          up:        ip link set up dev $IFACE
          post-down: ip addr del {{ interface.lan.address.ipv6 }} dev $IFACE || true
  - role: dhcp_server
    vars:
      dhcp_iface: '{{ interface.lan.name }}'
      dhcp_network: '{{ interface.lan.address.ipv4 | ipaddr("0") }}'
      dhcp_options:
        routers: '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        domain-name-servers:
          - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
          - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        domain-name: '"{{ site.tld if site.tld is defined else site.code }}"'
        ntp-servers: '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
      dhcp_range: '{{ interface.lan.dhcp_range }}'
      dhcp_lease_time:
        min: 300
        default: 21600
        max: 86400
  - role: dns_recursor
    vars:
      dns_iface: '{{ interface.lan.name }}'
      dns_listen:
        - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        - '{{ interface.lan.address.ipv6 | strip_prefixlen }}'
      dns_acl:
        - '{{ interface.lan.address.ipv4 | ipaddr("0") }}'
        - '{{ interface.lan.address.ipv6 | ipaddr("0") }}'
      dns_zones: '{{ site.dns | merge({ ".": site_l3.dns }) }}'
  - role: dns_authoritative
    vars:
      dns_zones: '{{ site.dns }}'
  - role: radvd
    vars:
      ra_iface: '{{ interface.lan.name }}'
      ra_default_lifetime: 1200
      ra_prefixes:
        - prefix: '{{ interface.lan.address.ipv6 | ipaddr("network/prefix") }}'
          lifetime:
            preferred: 300
            valid: 600
      ra_dns_servers:
        - '{{ interface.lan.address.ipv6 | strip_prefixlen }}'
