---
# Prerequisites
- name: Ensure fastd is installed
  apt:
    name: fastd
    state: present
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - patch
      - cron
      - jq
      - socat
  tags: mesh_vpn

- name: Ensure firewall allows fastd traffic
  template:
    src: etc/iptables.d/500-Allow-fastd
    dest: /etc/iptables.d/500-Allow-fastd
  notify:
    - restart firewall
  tags: mesh_vpn, firewall

# Config
- name: Ensure fastd peer directory exists
  file:
    path: "/etc/fastd/mvpn-{{ site.code }}/peers"
    state: directory
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure fastd config exists
  template:
    src: etc/fastd/mvpn/fastd.conf.j2
    dest: "/etc/fastd/mvpn-{{ site.code }}/fastd.conf"
  notify:
    - restart fastd
  tags: mesh_vpn

# Peers
- name: Ensure scripts are installed
  copy:
    src: "usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  with_items:
    - validate_fastd_keys
    - update_git_repo
    - fastd_query
  tags: mesh_vpn, fastd_keys

- name: Ensure fastd key update script is installed
  template:
    src: "{{ 'usr/local/bin/fastd_update_keys_{{ site.code }}.j2' }}"
    dest: "/usr/local/bin/fastd_update_keys_{{ site.code }}"
  tags: mesh_vpn, fastd_keys

- name: Ensure scripts are executable
  file:
    path: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - validate_fastd_keys
    - update_git_repo
    - fastd_update_keys_{{ site.code }}
    - fastd_query
  tags: mesh_vpn, fastd_keys

- name: Ensure fastd key directory is up to date
  shell: "/usr/local/bin/fastd_update_keys_{{ site.code }}"
  register: key_update
  changed_when: '"Installing changed key" in key_update.stdout'
  tags: mesh_vpn, fastd_keys, update_fastd_keys

- name: Ensure fastd key repo update cronjob is installed
  cron:
    name: "fastd_update_keys_{{ site.code }}"
    job: "/usr/local/bin/fastd_update_keys_{{ site.code }}"
    minute: '*/5'
  tags: mesh_vpn, fastd_keys

# Service
- name: Ensure fastd init file is patched
  patch:
    src: patches/0000-fastd-init-wait-for-process.patch
    dest: /etc/init.d/fastd
    basedir: /
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure fastd service is enabled and started
  service:
    name: fastd.service
    enabled: yes
    state: started
  tags: mesh_vpn
